FROM golang:1.13.8 AS build-env

RUN go get github.com/go-delve/delve/cmd/dlv

ADD . /dockerdev
WORKDIR /dockerdev

RUN go build -gcflags="all=-N -l" -o /server

# Final Stage
FROM nginx:latest

EXPOSE 80

WORKDIR /
COPY --from=build-env /go/bin/dlv /
COPY --from=build-env /dockerdev/config.yaml /config.yaml
COPY --from=build-env /server /

CMD ["/dlv", "--listen=:40000", "--headless=true", "--api-version=2", "--accept-multiclient", "exec", "/server"]